### ISSUE TITLE
Test Cases With Strings That Contain Escaped Double-Quotes are Not Run

### ISSUE THREAD

**Issue by JasonBock** [nunit/nunit3-vs-adapter#1347]
# To Reproduce

* Create a new project that targets .NET 10. Specifically, ensure the project file has this setup:

```xml
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<EnableNUnitRunner>true</EnableNUnitRunner>
		<LangVersion>preview</LangVersion>
		<TargetFramework>net10.0</TargetFramework>
		<TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.0" />
		<PackageReference Include="NUnit" Version="4.4.0" />
		<PackageReference Include="NUnit.Analyzers" Version="4.10.0" >
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="NUnit3TestAdapter" Version="5.2.0" />
	</ItemGroup>
</Project>
```

* Add a test to the project:

```c#
using NUnit.Framework;

namespace NUnitIssue;

public static class TestIssue
{
    [TestCase("public class Test { public void Foo(string a = \"c\") { } }", false)]
    public static void TestLength(string input, bool expected) =>
        Assert.That(input.Length % 2 == 0, Is.EqualTo(expected));
}
```

# Expected

The test runs and passes.

# Actual

The test doesn't run at all.

# Commentary

If I change the test case to this:

```c#
[TestCase("public class Test { public void Foo(string a = c) { } }", false)]
```

That passes. Note that in the project, I'm enabling `EnableNUnitRunner` and `TestingPlatformDotnetTestSupport`. If those are `false`, the test case runs as expected. Something with the escaped double-quote seems to be confusing NUnit such that it won't run the test if the testing platform bits are enabled.

Note: you may not need to be targeting .NET 10 and a preview version of the language for this to show up as the issue seems to be related to testing platform enablement and not a version of .NET and/or the language per-se.

**Comment by mikkelbu** [comment]
Thanks for the report @JasonBock . How are you running the tests? From VS, `dotnet test` or something third? That being said, I suspect the problem could be in the nunit3-vs-adapter or in the new testing planform, so should be moved to another repo, but for now let's just keep it here until we are sure

**Comment by OsirisTerje** [comment]
This is a problem connected with a) the adapter b) the use of MTP (Microsoft Test Platform) - which happens when you add `EnableNUnitRunner`.  

The problem is fixed in version 6.0 of the adapter, you can use version 6.0.0-alpha.100 from the myget feed  https://www.myget.org/F/nunit/api/v3/index.json  to verify.

A runnable repro (where I added your test) can be found at https://github.com/nunit/nunit3-vs-adapter.issues/tree/master/Issue1241/Repro1  

Also see  https://github.com/nunit/nunit3-vs-adapter/issues/1332  and https://github.com/nunit/nunit3-vs-adapter/issues/1241

Version 6.0 is due for release Nov 1.

**Comment by OsirisTerje** [comment]
I'll add this too to the release notes as fixed, since the symptoms are different, but root cause the same.

**Comment by JasonBock** [comment]
> This is a problem connected with a) the adapter b) the use of MTP (Microsoft Test Platform) - which happens when you add `EnableNUnitRunner`.
> 
> The problem is fixed in version 6.0 of the adapter, you can use version 6.0.0-alpha.100 from the myget feed https://www.myget.org/F/nunit/api/v3/index.json to verify.
> 
> A runnable repro (where I added your test) can be found at https://github.com/nunit/nunit3-vs-adapter.issues/tree/master/Issue1241/Repro1
> 
> Also see [#1332](https://github.com/nunit/nunit3-vs-adapter/issues/1332) and [#1241](https://github.com/nunit/nunit3-vs-adapter/issues/1241)
> 
> Version 6.0 is due for release Nov 1.

Hey @OsirisTerje FWIW I updated my packages to this:

```xml
<PackageVersion Include="NUnit" Version="4.4.0" />
<PackageVersion Include="NUnit.Analyzers" Version="4.11.2" />
<PackageVersion Include="NUnit3TestAdapter" Version="6.0.0-beta.1" />
```

And I'm still seeing the issue.

**Comment by OsirisTerje** [comment]
@JasonBock I checked this again, with beta.3 and it works as it should.  Please check your settings as per the screenshot below.

Repro code here:  https://github.com/nunit/nunit3-vs-adapter.issues/tree/master/Issue1241/Repro1

Checked with both net8 and net10

<img width="2085" height="1567" alt="Image" src="https://github.com/user-attachments/assets/0b4814af-fb5d-4d6b-a903-b2e218d6dddc" />
