### ISSUE TITLE
Console.WriteLine() does not write to console when running`dotnet test`

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit3-vs-adapter#343]
@ayoung commented on [Thu Jun 15 2017](https://github.com/nunit/nunit/issues/2257)

I'm running `dotnet test` targeting netcorapp1.1. Within the test I'm executing a console write but that text never makes it to the output on the screen.

---

@rprouse commented on [Fri Jun 16 2017](https://github.com/nunit/nunit/issues/2257#issuecomment-309188356)

Are you using `dotnet-test-nunit` or the alpha of the adapter for your tests? In other words, `project.json` or `csproj`? This issue needs to be moved to the correct repository.

---

@ayoung commented on [Sat Jun 17 2017](https://github.com/nunit/nunit/issues/2257#issuecomment-309199974)

i am using the alpha adapter. csproj.

---

@rprouse commented on [Sat Jun 17 2017](https://github.com/nunit/nunit/issues/2257#issuecomment-309222218)

Thanks, I am going to move to that repository then. Please track it there.

**Comment by cincuranet** [comment]
Any workaround for this for now?

**Comment by rprouse** [comment]
Sorry, nothing yet.

**Comment by giggio** [comment]
This makes showing the errors a pain. Microsoft is directing the problem to the test adapter implementers, see: https://github.com/Microsoft/vstest/issues/799

**Comment by sebwills** [comment]
I am finding that if a test is successful, its console output is not displayed. But if it fails, after the failure message and Stack Trace, the output contains a line "Standard Output Messages:" followed by the console output from that test alone. Is this behaviour deliberate? If so is it configurable?

**Comment by dariusdamalakas** [comment]
Run into same issue as well. See https://github.com/nunit/nunit3-vs-adapter/issues/132#issuecomment-358083248

**Comment by dariusdamalakas** [comment]
@sebwills apparently, the `Standard Output Messages` shows different output depending on whether the exception was thrown during test execution or not.  I will need to repro this properly, and get a PR which would show this.  In the meantime, at least there is a hacky workaround to see the `Console.Writeline` messages.

**Comment by Thaina** [comment]
I have the same problem and would like this to be fixed too

**Comment by scriplit** [comment]
For info, "dotnet test -v n" adds a lot of crap to the console, but at least diplays the stdout lines.

**Comment by Thaina** [comment]
@scriplit And it is a lot of crap that really just a crap without anything useful

**Comment by rprouse** [comment]
We can't add to the command line options for `dotnet test` and the adapter can't even get access to most of the command line options, so it makes it hard to configure, but we should probably be outputing to the console when the messages are received similar to we do in NUnit Console.

**Comment by dhowe** [comment]
Same issue... though for me I don't see stdout lines, even with  "-v n" flag
Any update?

**Comment by chriswolf-nrg** [comment]
Why does NUnit-3 disable console output?  It also seems to disable logging too.  Is there a way to make NUnit not do that?

**Comment by jnm2** [comment]
Even though it can't access `dotnet test` arguments, one thing the adapter can do is read options from a .runsettings file.

**Comment by soyemi** [comment]
> Same issue... though for me I don't see stdout lines, even with "-v n" flag
> Any update?

Try use `NUnit.Framework.TestContext.Progress.WriteLine()`, it works for me with `dotnet test`.

**Comment by JustoSenka** [comment]
Well it could work it is tests which write to console. Bu we have no control of what the application we are testing writes to console. It's still a bug, seems to be trivial to fix, but nobody fixed it in years

**Comment by jnm2** [comment]
@OsirisTerje should this be up for grabs? Sounds like there's a possibility that this is trivial.

**Comment by OsirisTerje** [comment]
@jnm2 Anyone can grab this of course.  Tip:  Enable dump file, and look at what NUnit actually sends to the adapter.  Anything going there is sent to the EventListener, and once there it can be sent anywhere.

**Comment by richardthombs** [comment]
Can you please bump the priority of this a bit? Still no progress after nearly a year since the last comment.

**Comment by OsirisTerje** [comment]
@richardthombs  Can you please check this alpha version:  https://www.myget.org/feed/nunit/package/nuget/NUnit3TestAdapter/3.17.0-dev-01324 

The console output is fixed there.

**Comment by roji** [comment]
@OsirisTerje have just tested with NUnit3TestAdapter 3.17.0-dev-01324 and I still cannot see Console.WriteLine with dotnet test (on either Windows or Linux). Note that everything seems fine on all IDE test runners (Rider, VS).

Repo with the test: https://github.com/roji/TestConsoleTests/

**Comment by OsirisTerje** [comment]
@roji Just tried your repo, and I **do** see the correct output.  Changed the console.writeline to say "Hello world from NUnit" and "Hello world from XUnit", and I do see the NUnit output, but not the XUnit output.
![343-1](https://user-images.githubusercontent.com/203432/75095219-f4457400-5592-11ea-9d58-e2a5f4b9aecd.jpg)

**Comment by roji** [comment]
@OsirisTerje ah I see, thanks - with the verbosity set to normal I can see the message as well. Seems a bit questionable to not write output by default, but I'm guessing that's unrelated to NUnit.

**Comment by OsirisTerje** [comment]
@roji  Agree with the verbosity, that is the dotnet test default that imho should be normal, but for some reason is not.  And as you assume, we can't do anything with that from the adapter side.  Could be worthwhile an issue at the dotnet repo though.

**Comment by roji** [comment]
Opened https://github.com/dotnet/sdk/issues/10706

**Comment by OsirisTerje** [comment]
@roji  Beta released on Nuget, see https://www.nuget.org/packages/NUnit3TestAdapter/3.17.0-beta.1 . Please check that it works :-)

**Comment by roji** [comment]
Great! Gave it a try, and I can confirm that I can see Console.WriteLine (when `-v n` is specified).

**Comment by giggio** [comment]
I just tried it with `3.17.0-beta.2` and it is working fine (with `-v n`). Waiting for the stable release now.
I hope https://github.com/dotnet/sdk/issues/10706 closes soon so this becomes better.

**Comment by OsirisTerje** [comment]
@giggio  Thanks!

**Comment by alfreql** [comment]
Hi I'm using net5.0, NUnit-3.13.2 and NUnit3TestAdapter-4.1.0 and `Console.WriteLine("HELLO!!!")` is not working.  I still cannot see the output HELLO!!! on the console.  I'm running like this: `dotnet test SomeExample.sln -v n`

**Comment by OsirisTerje** [comment]
@alfreql Yeah, this is annoying, see https://github.com/dotnet/sdk/issues/10706  .  You can get it out doing:

```cmd
dotnet test v n --logger "Console;verbosity=normal"
```

**Comment by alfreql** [comment]
Thanks!!! Also without -v n works (and avoid all the verbosity):
 `dotnet test SomeExample.sln --logger:"console;verbosity=detailed"`

**Comment by OsirisTerje** [comment]
Hmm.... cool and right you are, never tried removing that one :-)  

That means one could also set the logger in a .runsettings file, see https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2022#loggerrunsettings-element  and then do

```cmd
dotnet test -s .runsettings
```

The .runsettings would then be:

```xml
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
    <LoggerRunSettings>
        <Loggers>
            <Logger friendlyName="console" enabled="True">
                <Configuration>
                    <Verbosity>normal</Verbosity>
                </Configuration>
            </Logger>
        </Loggers>
    </LoggerRunSettings>
</RunSettings>
```

PS:  If you only have the sln file in the folder, you don't need to specify it

**Comment by OsirisTerje** [comment]
Just to have it said:  There is something that happened, because the 3.17 DID output the Console, but right now it doesn't, neither for 3.17 or for 4.X.

Not sure what, but I'll look into it.

**Comment by OsirisTerje** [comment]
This will be fixed in 4.2

**Comment by turowicz** [comment]
It still doesnt work @OsirisTerje

**Comment by stevenaw** [comment]
@turowicz Does this issue describe what you're seeing?
https://github.com/nunit/nunit3-vs-adapter/issues/1243

If not, can you please create a new issue with a clear reproduction steps and adapter version info for your case? This particular issue is a few years old meaning it could be likely the behavior you're seeing has a different underlying cause
