### ISSUE TITLE
NUnit parallelization is not working.

### ISSUE THREAD

**Issue by harsht92** [nunit/nunit3-vs-adapter#416]
I am working with NUnit 3.8.1 with TestAdapter version 3.9.0 and visual studio VS15 target framework is 4.6.1 

I am trying to run test cases in parallel and they are in different TestFixtures. I have used Parallelizable for both the fixtures. One fixture is running in Chrome and Other is running in Firefox. The TestFixtureSetup is like that it has to login into the site for performing the test case.

Issue:
The TestFixtures are opening in parallel(i.e., both chrome and Firefox are opening in parallel) but it is logging in any one of the browser and keeping the other on the login page. Once the logged in fixture is complete, both the browsers are going off and after sometime it is opening the browser which did not allow the login last time and running the test cases in that.

Please help!!!

**Comment by OsirisTerje** [comment]
Can you please upload a repro project?
Make it as small as you can, it should compile "as is".

**Comment by CharliePoole** [comment]
This is most likely a framework issue, since it's the framework that does parallelization. It sounds like some of those things we fixed with 3.9, so you should try that.

**Comment by OsirisTerje** [comment]
@harsht92 Can you confirm it works for you with NUnit 3.9 ?

**Comment by harsht92** [comment]
Yeah, i tried checking this with Nunit 3.9, it is still not working for the project on which i was working.
Also, as per @OsirisTerje comment , I tried creating demo project for the same and it allowed login in both the fixtures.
I am still checking my issue project code because in that i am using an abstract class for login.

**Comment by OsirisTerje** [comment]
@harsht92 And does the demo project also fail if you add that abstract class to it?

**Comment by harsht92** [comment]
Yes, this worked. I got the issue, and the issue is the abstract class that is creating the instance of the browser.
Thanks much.. :)
