### ISSUE TITLE
Test cases are skipped with TestCaseSource under Visual Studio 2019

### ISSUE THREAD

**Issue by LazarLashev** [nunit/nunit3-vs-adapter#676]
Running latest versions of Visual Studio 2019 and NUnit (Visual studio 2019 16.3.5, NUnit 3.12.0, NUnit3TestAdapter 3.15.1)

Test with a test source:

```
[Test]
[TestCaseSource(nameof(TestCases))]
public async Task When_InvalidRequest_ReturnsValidationError(PlayerBalancesRequest request, string siteCode, string correlationToken)
{
   ...
}

public class PlayerBalancesRequest
{
    public long PlayerId { get; set; }
    public string Token { get; set; }
    public string CurrencyCode { get; set; }
}

private static object[] TestCases()
{
    return new object[]
    {
        new object[] { new PlayerBalancesRequest(), null, null },
        new object[] { new PlayerBalancesRequest { PlayerId = 0, Token = GameToken, CurrencyCode = CurrencyCode }, SiteCode, CorrelationToken },
        new object[] { new PlayerBalancesRequest { PlayerId = PlayerId, Token = null, CurrencyCode = CurrencyCode }, SiteCode, CorrelationToken },
        new object[] { new PlayerBalancesRequest { PlayerId = PlayerId, Token = GameToken, CurrencyCode = null}, SiteCode, CorrelationToken },
        ...
    };
}
```

I have 15 test cases in the test case source. Visual Studio shows all of them in the Test Explorer, but NUnit always runs just 3 of them. Always the same 3, and the rest are skipped. If I remove these 3, then it runs no tests. As a separate issue, if I leave just 1 test case in the test case source, it will think this `object[3]` that is returned are 3 separate test cases (PlayerBalancesRequest, string and string) and will run the test 3 times with just 1 parameter, failing because the test requires 3 parameters.

**Comment by OsirisTerje** [comment]
@CharliePoole Not directly, but after the last big related fix, I have at least 3 hanging bugs which should have been fixed by the same.  I have asked the MS PG about this one in particular since the stack trace looks unknown to the adapter.  I am 99.9% sure nothing is being sent out from the discovery phase with the execution, but we do build up a cache, so there can be something there. 

I'll work through this one and see if I can catch a trace from it.

**Comment by klreeher** [comment]
I believe I'm also running into this bug.  I have an example project with test @ https://github.com/klreeher/nunitbugexample01/

This repo targets netcoreapp3, and my original repo targets v4.6.1. In the v4.6.1 framework repo, I tried the 3.16.0-dev test adapter, with no change. 

My specific example test shows a TestCaseSource that uses the following:

```
        public static IEnumerable TestCases
        {
            get
            {
                yield return new TestCaseData("bob@bob.com").Returns(true); // not skipped
                yield return new TestCaseData(Faker.InternetFaker.Email()).Returns(true); //skipped
                yield return new TestCaseData(Faker.InternetFaker.Domain()).Returns(false); // sometimes not skipped, if I clean and delete my obj/bin files and am very very good???
                yield return new TestCaseData(GetRandomNaughtyString()).Returns(false); //skipped
            }
        }
```

**Comment by mikkelbu** [comment]
Hi @klreeher. I just tried your example project, and it is a different issue than described above. The problem is that the test execution in VS is a two-phase run, one for discovery and one for execution. So when 
```csharp
                yield return new TestCaseData(Faker.InternetFaker.Email()).Returns(true); //skipped
                yield return new TestCaseData(Faker.InternetFaker.Domain()).Returns(false); // sometimes not skipped, if I clean and delete my obj/bin files and am very very good???
                yield return new TestCaseData(GetRandomNaughtyString()).Returns(false); //skipped
```
is executed during the discovery it will find testcases with certain values, but when you try to execute these tests then the data will not match for the last three elements as these will have a new value. For GetRandomNaughtyString you can either use a seeded randomizer or perhaps use NUnits own random class via `TestContext.CurrentContext.Random`. For Faker you can probably also provide a seed to make the values the same in the discovery and in the execution.

The issue #97 has more information on the two-phase run.

**Comment by CharliePoole** [comment]
Note that issue #97 was closed as fixed __but that the fix assumes__ you are using NUnit's own randomizer at least as an initial seed. What happens is that the adapter saves the seed used for discovery in a temp file and re-seeds it for execution.

It's a constraint on the adapter that discovery and execution run at different times in two different processes. The only communication possible is through the file system but we must still find or generate the same exact tests in discovery and execution. Currently, we simply save the random seed. A more general approach would be to save and restore the entire tree of discovered tests for reach assembly, but that's kind of a big deal!

**Comment by klreeher** [comment]
@mikkelbu @CharliePoole thank you both for the info! Switching my fake data to use the nunit random seed solved my problem.

**Comment by OsirisTerje** [comment]
This bug is a duplicate of #685 .

**Comment by OsirisTerje** [comment]
@LazarLashev This bug works with 3.16.0.  In upcoming 3.16.1 you will net to add a runsettingsfile and set the following true:  UseParentFQNForParametrizedTests
You might possibly also need to set UseNUnitIdforTestCaseId to true. 
Default for both will be false in 3.16.1
When  it is released documentation will be found here: https://github.com/nunit/docs/wiki/Tips-And-Tricks

**Comment by OsirisTerje** [comment]
This issue is resolved by Version 3.16.1 which is released now on [nuget.org](https://www.nuget.org/packages/NUnit3TestAdapter/3.16.1) and VSIX on [Visual Studio marketplace](https://marketplace.visualstudio.com/items?itemName=NUnitDevelopers.NUnit3TestAdapter).  See [all issues resolved](https://github.com/nunit/nunit3-vs-adapter/issues?q=is%3Aissue+milestone%3A3.16.1+is%3Aclosed) and  [Release notes](https://github.com/nunit/docs/wiki/Adapter-Release-Notes) for details.

**Comment by troyxli** [comment]
@OsirisTerje , could you please share an example of how to set these two config values to true: UseParentFQNForParametrizedTests and UseNUnitIdforTestCaseId to true?

**Comment by Arturace** [comment]
Either the bug still exists or my `.runsettings` is invalid, because my test cases still get skipped when I run all test, or even the parent node:
![image](https://user-images.githubusercontent.com/36833825/75361470-577e2180-5885-11ea-8a6b-db07955e72b4.png)

It clearly sees the custom names and puts them under the function decorated with the `TestCaseSource` attribute, but doesn't run them.
I have the 3.16.1 nuget version of NUnit. VS2019 16.4.5.

Here is my .runsettings (simplified):
```
<RunSettings>
  <RunConfiguration>
    ...
    <NUnit>
      <UseNUnitIdforTestCaseId>True</UseNUnitIdforTestCaseId>
      <UseParentFQNForParametrizedTests>True</UseParentFQNForParametrizedTests>
    </NUnit>
     ...
</RunSettings>
```

**Comment by stepagrus** [comment]
If this is an bug, then the bug still exists 😫

![image](https://user-images.githubusercontent.com/28809301/114173853-9e2fbd80-9959-11eb-94ec-17dc9338491b.png)

![image](https://user-images.githubusercontent.com/28809301/114173950-bd2e4f80-9959-11eb-83d8-8c9407a7b416.png)

![image](https://user-images.githubusercontent.com/28809301/114174012-d505d380-9959-11eb-8d49-d3b88f8f58bf.png)

![image](https://user-images.githubusercontent.com/28809301/114174378-59585680-995a-11eb-87df-a76fe0cb3ca8.png)

![image](https://user-images.githubusercontent.com/28809301/114174449-73923480-995a-11eb-90b4-34c8fb5b3e10.png)

**Comment by panmanphil** [comment]
Also experiencing this. NUnit3TestAdapter 3.17.0. VS 2019 was just updated to the most recent, all extensions at the latest version.

**Comment by OsirisTerje** [comment]
@panmanphil @stepagrus  Can you create a small repro for this?

And, you see the ```[11/6/2019 9:57:55.797 AM Error] System.ArgumentException: An item with the same key has already been added.```

**Comment by panmanphil** [comment]
I do not see the system.argumentexception in the Tests output in VS, no. 
```
        private static Guid FixedPayerId = Guid.NewGuid();
        private static TestCaseData[] PayerMatchCases =
        {
            new TestCaseData(Guid.NewGuid(), Guid.NewGuid()).SetName("DifferentPayerIds"),
            new TestCaseData(FixedPayerId, FixedPayerId).SetName("SamePayerId")
        };
        [TestCaseSource(nameof(PayerMatchCases))]
        public async Task Process_ShouldMatchExistingPayers(Guid payerId, Guid existingPayerId)
        { ... }
```

**Comment by OsirisTerje** [comment]
Ok, can you create a small repro and either upload it here, or add it to a repo, e.g. https://github.com/nunit/nunit3-vs-adapter.issues/tree/master/done/Issue676   If that repro fails for you, then that is ok, but if not, then this might be another issue, and then it should be a new issue too, and a new repro folder there too.

**Comment by panmanphil** [comment]
https://github.com/nunit/nunit3-vs-adapter.issues/pull/4

Also, the existing test case using `object[]` also displays incorrectly now and fails to run all of the test cases. After deleting my obj folder my test cases actually do run, but aren't grouped correctly the the base name shows on a separate line as not having run.

**Comment by OsirisTerje** [comment]
i've merged your PR and I get this:
![image](https://user-images.githubusercontent.com/203432/115047650-0261fc80-9ed9-11eb-9923-440e9071d644.png)

**Comment by OsirisTerje** [comment]
What do you mean is wrong here?

**Comment by OsirisTerje** [comment]
Btw, the other displays also like it should:
![image](https://user-images.githubusercontent.com/203432/115047849-35a48b80-9ed9-11eb-8dc5-4e95c5ffee02.png)

Mind you, this is controlled through the .runsettings file,  the properties are 
```xml
  <UseParentFQNForParametrizedTests>true</UseParentFQNForParametrizedTests>
  <UseNUnitIdforTestCaseId>false</UseNUnitIdforTestCaseId>
```

**Comment by panmanphil** [comment]
There are 11 test cases for the PlayersBalance tests, 2 for the new test cases. You may have different settings, but I'm expecting these test cases to follow exactly what happens with `[TestCase(xxx)]` which works correctly. I am getting tests not run and not grouped as yours is showing and have the .runSettings as part of the project unchanged

![image](https://user-images.githubusercontent.com/2211089/115053830-2c013080-9ea5-11eb-8f20-ce468a6e250e.png)

**Comment by OsirisTerje** [comment]
The way your results look means the .runsettings file is not enabled.  
Check the settings:
![image](https://user-images.githubusercontent.com/203432/115074843-85e01580-9efa-11eb-9f44-80a55fda1901.png)
Take a new pull from the repo, I have upped the verbosity to 5.
The look at the output window, and verify that the redlined setting actually **is** true.
![image](https://user-images.githubusercontent.com/203432/115074964-af993c80-9efa-11eb-86ff-dc839d161ec3.png)

If I turn it off, I get exactly the same as you have:
![image](https://user-images.githubusercontent.com/203432/115075159-f1c27e00-9efa-11eb-9c05-86dc159c76af.png)

**Comment by panmanphil** [comment]
I did not have that checkbox checked in Test->general and with it checked I get the same results as you. Thanks for that. 

At least all the tests are run. The display is still "wrong", or at least surprising in that instead of having the name of the test, `Process_ShouldMatchExistingGuids`, as the root of the node and the test cases  underneath it, and the count showing the number of test cases, we get the name of the first test case as the root of the node and a count of 1. I'd have expected this to work just like `[TestCase()` where the NUnit Adapter takes the test method name as the name of the root node, and puts a new line for each test case run underneath it. 

I'd have expected to see `Process_ShouldMatchExistingGuids` as the root node under the test class name like it works with TestCase. If you say, that's just the way it is going to be, I'll be fine I'm sure.

**Comment by OsirisTerje** [comment]
Good to hear it "works".  
It's not the end of the road.  We want it to be the way you describe, but we need our Microsoft friends to fix the FQN issue first.  Hopefully it will not be too long. Once we have that, a lot of these issues, which we call FQN issues, will be resolved, and the test explorer display should be as you describe above.

**Comment by OsirisTerje** [comment]
About your last sentence:  The adapter can not control the test explorer, so it is **not** the adapter that adds lines. The adapter returns a collection, and then the test explorer displays it as it seems fit.

**Comment by panmanphil** [comment]
So if the collection returned when using TestCaseSource looked just like the collection returned when using TestCase it would work? Or does the Test Explorer need to know the difference?

**Comment by OsirisTerje** [comment]
Yes, that is true, but note that it is the naming that causes the issues. The name of the test has to be kind of like a C# method, a Fully Qualified Name.

**Comment by OsirisTerje** [comment]
@panmanphil  I looked a bit more into the repro code today, and this is actually not really an FQN issue.   I am sorry for this oversight from my side.
This is the **"random"** issue.   The parameters used here is a Guid, and that Guid changes for every run.  Since the methods are actually called at least twice during execution, the creation of the Guid based parameters are changing.  What you see in the Test Explorer for the tests that are not running, is the result of the first run through (which might be the Real Time Discovery too - I'm not 100% sure about that, except that it doesn't help).  The guid you see will stay the same until the next time you do a **Rebuild all**.  IF you do that, they will change.  
But, and this is the important bit, every time you run the execution, the internal guids in the actual tests have got different values, and thus they don't match with the original ones, and are thus left in that state of 'not executed'.

If you pull down the latest version of the code, I have added two more tests, (and changed the runsetting back to default, btw).  

The original test is the same.  

Then you have the **ValidPlayerBalancesTest**, which doesn't use Guids, but are creating a repeatable pattern.  You will see that all of those are fine and green.

Then you have the **ModifiedPlayerBalancesTest**, where the Guids are used, but incremented using a repeatable way of doing that (idea from [StackOverflow](https://stackoverflow.com/questions/30404965/increment-guid-in-c-sharp) ).  As you can see the tests now are also all fine and green.

So, it boils down to the fact that all parameters to tests have to be repeatable over multiple runs.

![image](https://user-images.githubusercontent.com/203432/115126195-9ca36c80-9fcd-11eb-987c-5d4d7391ddc4.png)

**Comment by CharliePoole** [comment]
Repeatable "random" values in tests is exactly the problem `TestContext.Random` is intended to solve. The adapter at one time helped it do this by saving a seed value at discovery time and re-using the same value upon execution. Wouldn't this solve the particular problem we see here?

**Comment by OsirisTerje** [comment]
Yes, the use of `
```
TestContext.CurrentContext.Random.NextGuid()
```
also yields usable guids. 
I've pushed up code to the repo showing that too.

**Comment by gsonnenf** [comment]
Having the same issue with randomly generate TestCaseSource  (e.g. Fixture.Create<string>() )  being reported as 'not run' when running them using the MS Test Runner. They are reported as running just fine with the Resharper test runner.

**Comment by OsirisTerje** [comment]
@gsonnenf  Can you provide a small repro for this?

**Comment by gsonnenf** [comment]
@OsirisTerje 
https://github.com/gsonnenf/Gstc.Nunit.IssueDemo

**Comment by CharliePoole** [comment]
The example uses the .NET Random class to generate tests. It's a known limitation that NUnit's wrapper class, which is part of TestContext, must be used when running under Visual Studio. The adapter contains code to save the random seed used in discovery and re-use it in the execution phase.

**Comment by gsonnenf** [comment]
The work around is to use Resharper Test Runner so I don't have add additional code to use AutoFixture.  I just added the random in there to demonstrate it was not specific to AutoFixture.

But... if its a known issue, that can't be fixed, why ask for me to spend a half hour setting up a test case? -_-

**Comment by OsirisTerje** [comment]
@gsonnenf Sorry about that, but I assumed you had a case that was different from what was discussed above [your comment] - which talks about using the NUnit Random class.  If you just added it in the example, and it happens in other places (Autofixture?), then that would be interesting.  Without a code example it is very hard for us to understand what you're seeing.

**Comment by gsonnenf** [comment]
@OsirisTerje Well, the repo is posted, along with the pictures of what I'm seeing. The issues occurs with value types and strings. It doesn't appear to occur with objects, which is likely what you are using.

**Comment by OsirisTerje** [comment]
@gsonnenf Thanks!  I'll have a look at it :-)

**Comment by OsirisTerje** [comment]
@gsonnenf  There is something strange going on here.  I'll create a separate issue for this, and try to debug what this is.  This doesn't look like the standard random issue.

**Comment by moh-hassan** [comment]
I have the same problem when using `TestCaseSource` in vs2019 / vs2022 in **TEST EXPLORER**, when testcase include GUID
But **no problem** if I run the test from the terminal using the command `dotnet test`
and no problem when Run test using `Resharper.`
I think the problem is related to Test Explorer.

I use the next packages:
```
<PackageReference Include="NUnit" Version="3.13.2" />
<PackageReference Include="NUnit3TestAdapter" Version="4.2.1" />
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.0.0" />
<PackageReference Include="FluentAssertions" Version="5.10.0" />
```

**Comment by moh-hassan** [comment]
I did a workaround to fix the issue by using constant `Guid` values within `TestCaseSource`, like this
```
 private static Guid guid0 = new Guid("005bfef4-ff3d-4898-9b7d-cc6aab8db0eb");        
 private static Guid guid1= new Guid("8bfb35f0-9cad-4e19-ba01-cc09d7d47351");

//Then use these values in TestCaseSource
//avoid using Guid.NewGuid()  in TestCaseSource
```
Any trial to use `Guid.NewGuid()` in `TestCaseSource`, disable test case running.
But, as i said, it's only on vs2019 Test Explorere.
In Resharper or running test from terminal it's working fine.

**Comment by gsonnenf** [comment]
It appears it the random inputs might be a problem with the MS Test runner, that can't be fixed from the NUnit side. Perhaps someone should ask them to fix it so their VS built in tool can handle random inputs.

**Comment by OsirisTerje** [comment]
Do you mean this also happens with the MSTest framework?
It may also be dependent upon the use of the Real Time Test discovery feature.

**Comment by gsonnenf** [comment]
Ah! My mistake if that's where the issues lies. I may have incorrectly garnered from the entirety of the thread that the issue was elsewhere.

**Comment by moh-hassan** [comment]
After more investagation for the problem, I suggest the next solutions:

**Guid solution in `TestCaseSource`**
**Solution 1:**
use `TestContext.CurrentContext.Random.NextGuid()`  instead of  `Guid.NewGuid()`

```
public static IEnumerable<TestCaseData> GuidData
        {

            get
            {
                yield return new TestCaseData(1, Guid.NewGuid());  //test disabled
                yield return new TestCaseData(2, Guid.NewGuid());  //disabled                 
                yield return new TestCaseData(4, TestContext.CurrentContext.Random.NextGuid()); //working fine                
            }
        }
```
**Solution2**: 
use `SetName` to unify the testcase name in the discovery and execution stage
```
 public static IEnumerable<TestCaseData> GuidData
        {

            get
            {
                yield return new TestCaseData(1, Guid.NewGuid()).SetName("g0");  //fine
                yield return new TestCaseData(2, Guid.NewGuid()).SetName("g1");  //fine                
                yield return new TestCaseData(4, TestContext.CurrentContext.Random.NextGuid()); //fine
                
            }
        }
```
**Note**:
Using nunit.runsettings	 with `UseParentFQNForParametrizedTests`	has no effect

```
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
   <NUnit>
     <UseParentFQNForParametrizedTests>True</UseParentFQNForParametrizedTests>
     <UseNUnitIdforTestCaseId>True</UseNUnitIdforTestCaseId>
   </NUnit>  
</RunSettings>
```

**Comment by moh-hassan** [comment]
@gsonnenf
I resolved your issue by adding a `runsettings` file as described in my [suggested solution (solution1)](https://github.com/nunit/nunit3-vs-adapter/issues/676#issuecomment-1026386230)
 
The output of test Explorer is as shown below:
![gstc](https://user-images.githubusercontent.com/16975310/151960032-b45d13e5-2cf4-4512-8ee1-12d3672a23ef.JPG)
All 9 test cases are passed.

**Comment by jagdipafdb** [comment]
> Yes, the use of `
> 
> ```
> TestContext.CurrentContext.Random.NextGuid()
> ```
> 
> also yields usable guids. I've pushed up code to the repo showing that too. ![image](https://user-images.githubusercontent.com/203432/115139911-e7a49a80-a034-11eb-8abb-e5e833f9bd27.png)

This was the answer for me - and I think it needs to be highlighted more.

**Comment by CharliePoole** [comment]
@jagdipafdb It's fairly well described in the nunit framework docs...
https://docs.nunit.org/articles/nunit/writing-tests/Randomizer-Methods.html

Unfortunately, you need to know it's what you are looking for in order to find it. :-)

**Comment by Woudjee** [comment]
I believe I have the same problem:

![image](https://github.com/user-attachments/assets/309ca7d0-51f7-448c-9edc-3f29cb739a17)

![image](https://github.com/user-attachments/assets/8533abf0-81c0-4fa2-aa9b-a8036e231123)

![image](https://github.com/user-attachments/assets/c8e67e00-6261-4827-9811-0cfc4da2bf57)

Note that I have multiple test cases, but they are all skipped. I actually have about 500 unit tests I do like this, but this particular test case simply won't run. The crazy thing is that before the changes in my current branch, the code above simply worked, as well as for all my other unit tests. I reviewed all my changes extremely thoroughly, and there is nothing indicating any effect on this setup, including projecting the knowledge from this discussion onto the changes.

Initially, I was not using any runsettings (I have no experience with this). It is not clear to me if I did this correctly:

![image](https://github.com/user-attachments/assets/6def33b6-0bb1-4c66-b20e-6f119251951f)

![image](https://github.com/user-attachments/assets/106e4a35-e775-437e-83b4-9f7a4e46b35d)

I have now (honestly) wasted about 2 hours on this problem and I'm a little fed up, since it was working before and I'd rather spend my time on something else. Any suggestions?

**Comment by CharliePoole** [comment]
@Woudjee One minor suggestion... NUnit framework sometimes gets confused when the arguments are passed as an object[], even though that's still supported for legacy reasons. Try changing your source to return a TestCaseData[] instead. TestCaseData is the class designed precisely for the purpose of removing the ambiguity which arises when an object[] appears in a position where it might be the argument itself or an array of arguments.

Anyway, this may not be the solution, but it's what came to mind looking at your code.

**Comment by Woudjee** [comment]
@CharliePoole thank you for you quick reply. I have changed the object[] to TestCaseData[]. I must say that I like this syntax significantly more than the object[]. but unfortunately this did not fix the problem.

What is happening on the background? Because there is no error message or any information why the test won't run.

This does work (thereby clearly indicating that the objects are instantiated correctly):

![image](https://github.com/user-attachments/assets/87e78ed8-8425-4800-abc2-cf6cb77f19c6)

However, the code above defeats the purpose of the TestCaseSource setup.

**Comment by mikkelbu** [comment]
@Woudjee Does it work if you set the name of the testcase via `SetName` on `TestCaseData` to something fixed? 

Are there any useful information in the Output window under "Tests"?
![image](https://github.com/user-attachments/assets/f303882e-3fd3-490f-8129-0a4c82d0515b)

**Comment by Woudjee** [comment]
@mikkelbu I am unsure what you mean by the SetName since I cannot call any methods in this kind of setup:

![image](https://github.com/user-attachments/assets/759a5b67-1655-4a80-96b0-91c13d4a22e7)

And unfortunately, there is no information there. I have also ran builds and tests with 'verbose', but also here there was no information whatsoever.

**Comment by mikkelbu** [comment]
@Woudjee You can call the method on the instance returned by the constructor - so something like this
```csharp
        internal static TestCaseData[] GetTestCaseData =
        {
            new TestCaseData("Some data", 2).SetName("Test1"),
            new TestCaseData("Another data", 124).SetName("Test2"),
        };
```

**Comment by Woudjee** [comment]
@mikkelbu aha, I didn't check the return type and assumed it was void. I tried your suggestion, but unfortunately it didn't work :(

**Comment by Woudjee** [comment]
So I just tried to make a pull request, and apparantly my pipeline fails. This is more information than I had before!

![image](https://github.com/user-attachments/assets/dfd65ce6-9963-45d1-904c-0df24604c4ca)

The thing is, I am requesting three arguments:
![image](https://github.com/user-attachments/assets/a554e7fd-dc86-4e71-9b0a-e3c9e5c9e2d4)

And that I am providing three arguments:
![image](https://github.com/user-attachments/assets/7ec27eea-b1cd-4c94-b617-e4ace4b22044)

Any help is very much appreciated!

**Comment by Woudjee** [comment]
So, apparantly, I did make a small mistake. However, also apparantly, my test does run in the context of my pipeline, whereas it does not in the context of the VS test explorer. Why is this? (Quite a funny way to figure this out like this actually)

![image](https://github.com/user-attachments/assets/d4f7b236-d6ee-4c36-b165-e5ec1965c6a8)

**Comment by OsirisTerje** [comment]
> my test does run in the context of my pipeline, whereas it does not in the context of the VS test explorer. 

What do you mean?
